#
# x0dbit travis-ci config
#
language: perl
perl: 
  - "5.28"
os: linux

services:
#  - cassandra
#  - couchdb
  - elasticsearch
  - memcached
#  - mongodb
#  - mariadb
#  - mysql
#  - postgresql
#  - rabbitmq
#  - redis
#  - riak

install: 
  - cpanm --quiet --notest --skip-satisfied Acme::Include
  - cpanm --quiet --notest --skip-satisfied Number::Format
  - cpanm --quiet --notest --skip-satisfied XML::RSS::Parser
  - cpanm --quiet --notest --skip-satisfied POE::Component::IRC
  - cpanm --quiet --notest --skip-satisfied Chatbot::Eliza
  - cpanm --quiet --notest --skip-satisfied LWP::UserAgent
  - cpanm --quiet --notest --skip-satisfied Regexp::Common
  - cpanm --quiet --notest --skip-satisfied Digest::MD5
  - cpanm --quiet --notest --skip-satisfied pQuery
  - cpanm --quiet --notest --skip-satisfied DBI
  - cpanm --quiet --notest --skip-satisfied Switch

  #before_script:
#  - sudo apt install cpanminus

script:
#  - bash install.sh
  - perl x0dbot.pl -e
