#
# x0dbot travis-ci config
#
language: perl
perl: 
  - "5.28"
os: linux

install: 
  - cpanm --quiet --notest --skip-satisfied Chatbot::Eliza
  - cpanm --quiet --notest --skip-satisfied DBI
  - cpanm --quiet --notest --skip-satisfied Digest::MD5
  - cpanm --quiet --notest --skip-satisfied LWP::UserAgent
  - cpanm --quiet --notest --skip-satisfied Number::Format
  - cpanm --quiet --notest --skip-satisfied POE::Component::IRC
  - cpanm --quiet --notest --skip-satisfied pQuery
  - cpanm --quiet --notest --skip-satisfied Regexp::Common
  - cpanm --quiet --notest --skip-satisfied Switch
  - cpanm --quiet --notest --skip-satisfied XML::RSS::Parser
  - sudo apt install fortune

script:
  - perl x0dbot.pl --efnet &
