#
# x0dbit travis-ci config
#
language: perl
perl: 
  - "5.28"
os: linux

services:
#  - cassandra
#  - couchdb
  - elasticsearch
  - memcached
#  - mongodb
#  - mariadb
#  - mysql
#  - postgresql
#  - rabbitmq
#  - redis
#  - riak

#install: sudo apt install cpanminus

#before_script:
#  - sudo apt install cpanminus

script:
  - bash install.sh
  - perl x0dbot.pl -e